In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
import tensorflow as tf
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
data = pd.read_excel('/content/drive/MyDrive/data for raml/Foamboard/complex_data_train.xlsx')
data

,realPart_1,realPart_2,realPart_3,realPart_4,realPart_5,realPart_6,realPart_7,realPart_8,realPart_9,imaginaryPart_1,imaginaryPart_2,imaginaryPart_3,imaginaryPart_4,imaginaryPart_5,imaginaryPart_6,imaginaryPart_7,imaginaryPart_8,imaginaryPart_9
0,1.007849,0.969037,1.024370,1.020319,0.946247,1.137603,0.988407,0.928262,0.950598,-0.036472,0.048375,-0.013672,-0.010831,0.021401,-0.040638,0.019689,0.011398,0
1,1.014953,0.971555,1.028704,1.021329,0.944720,1.131834,0.981415,0.926503,0.926972,-0.039215,0.047689,-0.005834,-0.005610,0.023393,-0.039919,0.011036,0.008228,0
2,1.006961,0.969038,1.026541,1.011469,0.947114,1.137122,0.984167,0.939500,0.914930,-0.036946,0.049629,-0.008616,-0.011228,0.022735,-0.038102,0.014333,0.007815,0
3,1.008017,0.966748,1.027967,1.016508,0.949179,1.139574,0.982015,0.932956,0.883169,-0.036693,0.051222,-0.009646,-0.004815,0.021302,-0.045219,0.014656,0.008746,0
4,1.011708,0.970528,1.029756,1.021974,0.949140,1.137948,0.972849,0.930401,0.905443,-0.038893,0.047733,-0.010975,-0.007662,0.024319,-0.039880,0.016001,0.008950,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34170,1.064226,0.982698,1.076100,0.994657,0.964176,1.106229,0.871427,0.945673,0.941485,-0.032328,0.048418,-0.005560,-0.000035,0.001998,-0.030809,0.024011,-0.006888,0
34171,1.054993,0.974777,1.078024,0.997593,0.967279,1.113956,0.890118,0.935226,0.952207,-0.036753,0.047742,-0.009009,0.006049,0.007225,-0.039737,0.024404,-0.000891,0
34172,1.059890,0.981977,1.065516,0.998982,0.967444,1.105759,0.883269,0.946050,0.928207,-0.043242,0.047024,-0.006313,-0.006848,0.004119,-0.031992,0.030019,0.006624,0
34173,1.051640,0.974364,1.078555,0.995045,0.959843,1.117277,0.886355,0.950338,0.953459,-0.040171,0.056989,0.002291,0.007438,0.007342,-0.042583,0.019768,-0.012641,0
34174,1.054402,0.980393,1.069294,0.994522,0.953721,1.110437,0.883006,0.959893,0.907153,-0.035280,0.044689,-0.005376,0.006923,0.014120,-0.038214,0.021873,-0.010180,0

In [ ]:
X_train = data.iloc[:, :-1]
X_train = X_train.astype(float)
X_train

,realPart_1,realPart_2,realPart_3,realPart_4,realPart_5,realPart_6,realPart_7,realPart_8,realPart_9,imaginaryPart_1,imaginaryPart_2,imaginaryPart_3,imaginaryPart_4,imaginaryPart_5,imaginaryPart_6,imaginaryPart_7,imaginaryPart_8
0,1.007849,0.969037,1.024370,1.020319,0.946247,1.137603,0.988407,0.928262,0.950598,-0.036472,0.048375,-0.013672,-0.010831,0.021401,-0.040638,0.019689,0.011398
1,1.014953,0.971555,1.028704,1.021329,0.944720,1.131834,0.981415,0.926503,0.926972,-0.039215,0.047689,-0.005834,-0.005610,0.023393,-0.039919,0.011036,0.008228
2,1.006961,0.969038,1.026541,1.011469,0.947114,1.137122,0.984167,0.939500,0.914930,-0.036946,0.049629,-0.008616,-0.011228,0.022735,-0.038102,0.014333,0.007815
3,1.008017,0.966748,1.027967,1.016508,0.949179,1.139574,0.982015,0.932956,0.883169,-0.036693,0.051222,-0.009646,-0.004815,0.021302,-0.045219,0.014656,0.008746
4,1.011708,0.970528,1.029756,1.021974,0.949140,1.137948,0.972849,0.930401,0.905443,-0.038893,0.047733,-0.010975,-0.007662,0.024319,-0.039880,0.016001,0.008950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34170,1.064226,0.982698,1.076100,0.994657,0.964176,1.106229,0.871427,0.945673,0.941485,-0.032328,0.048418,-0.005560,-0.000035,0.001998,-0.030809,0.024011,-0.006888
34171,1.054993,0.974777,1.078024,0.997593,0.967279,1.113956,0.890118,0.935226,0.952207,-0.036753,0.047742,-0.009009,0.006049,0.007225,-0.039737,0.024404,-0.000891
34172,1.059890,0.981977,1.065516,0.998982,0.967444,1.105759,0.883269,0.946050,0.928207,-0.043242,0.047024,-0.006313,-0.006848,0.004119,-0.031992,0.030019,0.006624
34173,1.051640,0.974364,1.078555,0.995045,0.959843,1.117277,0.886355,0.950338,0.953459,-0.040171,0.056989,0.002291,0.007438,0.007342,-0.042583,0.019768,-0.012641
34174,1.054402,0.980393,1.069294,0.994522,0.953721,1.110437,0.883006,0.959893,0.907153,-0.035280,0.044689,-0.005376,0.006923,0.014120,-0.038214,0.021873,-0.010180

In [ ]:
#from sklearn.preprocessing import MinMaxScaler

# Create an instance of the MinMaxScaler
#scaler = MinMaxScaler()

# Fit the scaler on the training data and transform it
#X_train_normalized = scaler.fit_transform(X_train)

In [ ]:
y_train = pd.read_excel('/content/drive/MyDrive/data for raml/Foamboard/raml_train_label.xlsx')
y_train

       label_cell_train
0                  3.26
1                  3.26
2                  3.26
3                  3.26
4                  3.26
...                 ...
34170             24.92
34171             24.92
34172             24.92
34173             24.92
34174             24.92

[34175 rows x 1 columns]

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

# Print the shapes of the datasets
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_val shape:", X_val.shape)
print("y_val shape:", y_val.shape)

X_train shape: (27340, 17)
y_train shape: (27340, 1)
X_val shape: (6835, 17)
y_val shape: (6835, 1)

In [ ]:
data1 = pd.read_excel('/content/drive/MyDrive/data for raml/Foamboard/complex_data_test.xlsx')
data1

,realPart_1,realPart_2,realPart_3,realPart_4,realPart_5,realPart_6,realPart_7,realPart_8,realPart_9,imaginaryPart_1,imaginaryPart_2,imaginaryPart_3,imaginaryPart_4,imaginaryPart_5,imaginaryPart_6,imaginaryPart_7,imaginaryPart_8,imaginaryPart_9
0,1.012305,0.972172,1.026296,1.016650,0.947847,1.134835,0.982323,0.930380,0.937685,-0.039164,0.046862,-0.009439,-0.006971,0.024779,-0.040048,0.016395,0.007235,0
1,1.010253,0.970553,1.027181,1.019135,0.948038,1.137131,0.982069,0.928219,0.863446,-0.035757,0.050164,-0.010056,-0.008772,0.023683,-0.045929,0.016871,0.009243,0
2,1.013463,0.970150,1.024490,1.018884,0.948555,1.134773,0.978121,0.931944,0.952193,-0.034074,0.049585,-0.007781,-0.006668,0.018893,-0.043144,0.013264,0.009417,0
3,1.011341,0.970021,1.030543,1.014267,0.945452,1.142302,0.971199,0.934699,0.929501,-0.035443,0.050181,-0.009457,-0.008126,0.019987,-0.038488,0.014658,0.006232,0
4,1.012419,0.970239,1.029625,1.017302,0.950364,1.143033,0.972054,0.930408,0.967928,-0.034907,0.047643,-0.008541,-0.006486,0.018578,-0.040765,0.012930,0.011066,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8541,1.063297,0.981662,1.076662,1.000690,0.965119,1.108193,0.869906,0.940977,0.933208,-0.035661,0.057211,0.001235,-0.004616,0.005428,-0.036860,0.017023,-0.004952,0
8542,1.061020,0.988689,1.079395,0.992760,0.965000,1.105698,0.879946,0.931427,0.948163,-0.040387,0.049262,-0.006416,-0.009023,0.010203,-0.029657,0.028731,-0.003835,0
8543,1.053694,0.983957,1.078594,0.992842,0.964894,1.105321,0.884878,0.943180,0.902906,-0.037860,0.050049,0.001889,0.003491,0.009059,-0.043251,0.022829,-0.007579,0
8544,1.060048,0.979325,1.082809,0.992145,0.957731,1.109845,0.876148,0.950331,0.945208,-0.039420,0.046810,-0.009891,0.001551,0.009389,-0.034904,0.020801,0.004943,0
8545,1.062234,0.984940,1.079382,0.995422,0.955915,1.112954,0.878574,0.937037,0.892794,-0.043449,0.053946,-0.001433,0.005220,0.011072,-0.035596,0.022971,-0.014915,0

In [ ]:
X_test = data1.iloc[:, :-1]
X_test = X_test.astype(float)

X_test

,realPart_1,realPart_2,realPart_3,realPart_4,realPart_5,realPart_6,realPart_7,realPart_8,realPart_9,imaginaryPart_1,imaginaryPart_2,imaginaryPart_3,imaginaryPart_4,imaginaryPart_5,imaginaryPart_6,imaginaryPart_7,imaginaryPart_8
0,1.012305,0.972172,1.026296,1.016650,0.947847,1.134835,0.982323,0.930380,0.937685,-0.039164,0.046862,-0.009439,-0.006971,0.024779,-0.040048,0.016395,0.007235
1,1.010253,0.970553,1.027181,1.019135,0.948038,1.137131,0.982069,0.928219,0.863446,-0.035757,0.050164,-0.010056,-0.008772,0.023683,-0.045929,0.016871,0.009243
2,1.013463,0.970150,1.024490,1.018884,0.948555,1.134773,0.978121,0.931944,0.952193,-0.034074,0.049585,-0.007781,-0.006668,0.018893,-0.043144,0.013264,0.009417
3,1.011341,0.970021,1.030543,1.014267,0.945452,1.142302,0.971199,0.934699,0.929501,-0.035443,0.050181,-0.009457,-0.008126,0.019987,-0.038488,0.014658,0.006232
4,1.012419,0.970239,1.029625,1.017302,0.950364,1.143033,0.972054,0.930408,0.967928,-0.034907,0.047643,-0.008541,-0.006486,0.018578,-0.040765,0.012930,0.011066
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8541,1.063297,0.981662,1.076662,1.000690,0.965119,1.108193,0.869906,0.940977,0.933208,-0.035661,0.057211,0.001235,-0.004616,0.005428,-0.036860,0.017023,-0.004952
8542,1.061020,0.988689,1.079395,0.992760,0.965000,1.105698,0.879946,0.931427,0.948163,-0.040387,0.049262,-0.006416,-0.009023,0.010203,-0.029657,0.028731,-0.003835
8543,1.053694,0.983957,1.078594,0.992842,0.964894,1.105321,0.884878,0.943180,0.902906,-0.037860,0.050049,0.001889,0.003491,0.009059,-0.043251,0.022829,-0.007579
8544,1.060048,0.979325,1.082809,0.992145,0.957731,1.109845,0.876148,0.950331,0.945208,-0.039420,0.046810,-0.009891,0.001551,0.009389,-0.034904,0.020801,0.004943
8545,1.062234,0.984940,1.079382,0.995422,0.955915,1.112954,0.878574,0.937037,0.892794,-0.043449,0.053946,-0.001433,0.005220,0.011072,-0.035596,0.022971,-0.014915

In [ ]:
#X_test_normalized = scaler.transform(X_test)

In [ ]:
y_test = pd.read_excel('/content/drive/MyDrive/data for raml/Foamboard/raml_test_label.xlsx')
y_test

      label_cell_val
0               3.26
1               3.26
2               3.26
3               3.26
4               3.26
...              ...
8541           24.92
8542           24.92
8543           24.92
8544           24.92
8545           24.92

[8546 rows x 1 columns]

In [ ]:
X_train.shape

(27340, 17)

In [ ]:
y_train.shape

(27340, 1)

In [ ]:
X_test.shape

(8546, 17)

In [ ]:
y_test.shape

(8546, 1)

In [ ]:
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Model

def basic_model(input_shape):
    # Define the input shape (17 features)
    inputs = Input(shape=input_shape)

    # Define the layers of the model
    x = Dense(2048, activation='relu')(inputs)
    x = Dense(1024, activation='relu')(x)
    x = Dense(512, activation='relu')(x)
    x = Dense(256, activation='relu')(x)
    x = Dense(128, activation='relu')(x)
    x = Dense(64, activation='relu')(x)
    x = Dense(32, activation='relu')(x)
    outputs = Dense(1, activation='linear')(x)  # Output layer with linear activation for regression

    # Create the model
    model = Model(inputs=inputs, outputs=outputs)

    return model

In [ ]:
def custom_loss(y_true, y_pred):
    mae_loss = tf.keras.losses.mean_absolute_error(y_true, y_pred)
    mse_loss = tf.keras.losses.mean_squared_error(y_true, y_pred)
    total_loss = mae_loss + mse_loss
    return total_loss

In [ ]:
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint

reg_model =basic_model(input_shape=(17, 1))

learning_rate = 0.0001
optimizer = Adam(learning_rate=learning_rate)

In [ ]:
reg_model.compile(loss=custom_loss, optimizer= optimizer, metrics=['mae', 'mse'])

In [ ]:
checkpoint = ModelCheckpoint('best_model.h5', monitor='val_loss', save_best_only=True, mode='min')

In [ ]:
reg_model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_val, y_val), callbacks=[checkpoint])

Epoch 1/50
855/855 [==============================] - 16s 15ms/step - loss: 42.1765 - mae: 4.9278 - mse: 37.2487 - val_loss: 36.7603 - val_mae: 4.7536 - val_mse: 32.0067
Epoch 2/50
855/855 [==============================] - 12s 14ms/step - loss: 36.4648 - mae: 4.6545 - mse: 31.8103 - val_loss: 36.7416 - val_mae: 4.7472 - val_mse: 31.9944
Epoch 3/50
855/855 [==============================] - 14s 16ms/step - loss: 36.4784 - mae: 4.6531 - mse: 31.8253 - val_loss: 36.7023 - val_mae: 4.6755 - val_mse: 32.0267
Epoch 4/50
855/855 [==============================] - 13s 15ms/step - loss: 36.4437 - mae: 4.6488 - mse: 31.7949 - val_loss: 38.0326 - val_mae: 5.0325 - val_mse: 33.0001
Epoch 5/50
855/855 [==============================] - 12s 14ms/step - loss: 36.4630 - mae: 4.6518 - mse: 31.8112 - val_loss: 37.2311 - val_mae: 4.5370 - val_mse: 32.6941
Epoch 6/50
855/855 [==============================] - 13s 16ms/step - loss: 36.4433 - mae: 4.6499 - mse: 31.7935 - val_loss: 36.7794 - val_mae: 4.6252 - val_mse: 32.1542
Epoch 7/50
855/855 [==============================] - 12s 15ms/step - loss: 36.4606 - mae: 4.6506 - mse: 31.8099 - val_loss: 36.7452 - val_mae: 4.6394 - val_mse: 32.1057
Epoch 8/50
855/855 [==============================] - 12s 14ms/step - loss: 36.4494 - mae: 4.6518 - mse: 31.7976 - val_loss: 36.6909 - val_mae: 4.6657 - val_mse: 32.0252
Epoch 9/50
855/855 [==============================] - 13s 16ms/step - loss: 36.4311 - mae: 4.6511 - mse: 31.7800 - val_loss: 37.0846 - val_mae: 4.5523 - val_mse: 32.5324
Epoch 10/50
855/855 [==============================] - 12s 14ms/step - loss: 36.3803 - mae: 4.6459 - mse: 31.7343 - val_loss: 36.6689 - val_mae: 4.7193 - val_mse: 31.9496
Epoch 11/50
855/855 [==============================] - 13s 15ms/step - loss: 36.3820 - mae: 4.6472 - mse: 31.7348 - val_loss: 37.2774 - val_mae: 4.5365 - val_mse: 32.7410
Epoch 12/50
855/855 [==============================] - 13s 15ms/step - loss: 36.4037 - mae: 4.6476 - mse: 31.7561 - val_loss: 37.0207 - val_mae: 4.5532 - val_mse: 32.4675
Epoch 13/50
855/855 [==============================] - 13s 15ms/step - loss: 36.4134 - mae: 4.6501 - mse: 31.7632 - val_loss: 36.6454 - val_mae: 4.7111 - val_mse: 31.9343
Epoch 14/50
855/855 [==============================] - 14s 17ms/step - loss: 36.3943 - mae: 4.6506 - mse: 31.7437 - val_loss: 36.6680 - val_mae: 4.7323 - val_mse: 31.9357
Epoch 15/50
855/855 [==============================] - 13s 15ms/step - loss: 36.3603 - mae: 4.6505 - mse: 31.7098 - val_loss: 36.6403 - val_mae: 4.6624 - val_mse: 31.9779
Epoch 16/50
855/855 [==============================] - 13s 15ms/step - loss: 36.3982 - mae: 4.6496 - mse: 31.7486 - val_loss: 37.1540 - val_mae: 4.8806 - val_mse: 32.2734
Epoch 17/50
855/855 [==============================] - 14s 17ms/step - loss: 36.3463 - mae: 4.6451 - mse: 31.7013 - val_loss: 37.5617 - val_mae: 4.9653 - val_mse: 32.5964
Epoch 18/50
855/855 [==============================] - 13s 15ms/step - loss: 36.3164 - mae: 4.6450 - mse: 31.6714 - val_loss: 36.8490 - val_mae: 4.5788 - val_mse: 32.2702
Epoch 19/50
855/855 [==============================] - 13s 15ms/step - loss: 36.3328 - mae: 4.6447 - mse: 31.6881 - val_loss: 36.6114 - val_mae: 4.7319 - val_mse: 31.8795
Epoch 20/50
855/855 [==============================] - 13s 15ms/step - loss: 36.3376 - mae: 4.6456 - mse: 31.6920 - val_loss: 36.6437 - val_mae: 4.6261 - val_mse: 32.0176
Epoch 21/50
855/855 [==============================] - 13s 15ms/step - loss: 36.3086 - mae: 4.6415 - mse: 31.6670 - val_loss: 36.5606 - val_mae: 4.7158 - val_mse: 31.8448
Epoch 22/50
855/855 [==============================] - 13s 15ms/step - loss: 36.2861 - mae: 4.6423 - mse: 31.6439 - val_loss: 36.6645 - val_mae: 4.6037 - val_mse: 32.0609
Epoch 23/50
855/855 [==============================] - 12s 14ms/step - loss: 36.2409 - mae: 4.6391 - mse: 31.6018 - val_loss: 36.4973 - val_mae: 4.7130 - val_mse: 31.7844
Epoch 24/50
855/855 [==============================] - 12s 15ms/step - loss: 36.1402 - mae: 4.6330 - mse: 31.5072 - val_loss: 36.4399 - val_mae: 4.6901 - val_mse: 31.7498
Epoch 25/50
855/855 [==============================] - 13s 15ms/step - loss: 36.1421 - mae: 4.6330 - mse: 31.5091 - val_loss: 36.4159 - val_mae: 4.6326 - val_mse: 31.7833
Epoch 26/50
855/855 [==============================] - 13s 15ms/step - loss: 36.0906 - mae: 4.6279 - mse: 31.4627 - val_loss: 36.3721 - val_mae: 4.6406 - val_mse: 31.7315
Epoch 27/50
855/855 [==============================] - 13s 15ms/step - loss: 35.9983 - mae: 4.6209 - mse: 31.3775 - val_loss: 36.2557 - val_mae: 4.6278 - val_mse: 31.6279
Epoch 28/50
855/855 [==============================] - 13s 15ms/step - loss: 35.9079 - mae: 4.6122 - mse: 31.2958 - val_loss: 36.1562 - val_mae: 4.6252 - val_mse: 31.5309
Epoch 29/50
855/855 [==============================] - 13s 15ms/step - loss: 35.8327 - mae: 4.6034 - mse: 31.2293 - val_loss: 36.2285 - val_mae: 4.7438 - val_mse: 31.4847
Epoch 30/50
855/855 [==============================] - 13s 15ms/step - loss: 35.7264 - mae: 4.5932 - mse: 31.1332 - val_loss: 36.0563 - val_mae: 4.6735 - val_mse: 31.3828
Epoch 31/50
855/855 [==============================] - 14s 17ms/step - loss: 35.6905 - mae: 4.5836 - mse: 31.1069 - val_loss: 36.1334 - val_mae: 4.6763 - val_mse: 31.4571
Epoch 32/50
855/855 [==============================] - 13s 15ms/step - loss: 35.5435 - mae: 4.5701 - mse: 30.9733 - val_loss: 35.8772 - val_mae: 4.6895 - val_mse: 31.1877
Epoch 33/50
855/855 [==============================] - 12s 14ms/step - loss: 35.5198 - mae: 4.5642 - mse: 30.9556 - val_loss: 35.9016 - val_mae: 4.6828 - val_mse: 31.2188
Epoch 34/50
855/855 [==============================] - 13s 15ms/step - loss: 35.4094 - mae: 4.5524 - mse: 30.8570 - val_loss: 35.6846 - val_mae: 4.5986 - val_mse: 31.0861
Epoch 35/50
855/855 [==============================] - 13s 15ms/step - loss: 35.3332 - mae: 4.5422 - mse: 30.7909 - val_loss: 35.5861 - val_mae: 4.5296 - val_mse: 31.0565
Epoch 36/50
855/855 [==============================] - 13s 15ms/step - loss: 35.3094 - mae: 4.5380 - mse: 30.7713 - val_loss: 35.6125 - val_mae: 4.5206 - val_mse: 31.0919
Epoch 37/50
855/855 [==============================] - 14s 16ms/step - loss: 35.2073 - mae: 4.5303 - mse: 30.6771 - val_loss: 35.6812 - val_mae: 4.4983 - val_mse: 31.1829
Epoch 38/50
855/855 [==============================] - 13s 15ms/step - loss: 35.0717 - mae: 4.5156 - mse: 30.5561 - val_loss: 35.3341 - val_mae: 4.5287 - val_mse: 30.8054
Epoch 39/50
 15/855 [..............................] - ETA: 9s - loss: 33.9917 - mae: 4.3819 - mse: 29.6097

In [ ]:
reg_model.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_3 (InputLayer)        [(None, 17, 1)]           0

 dense_12 (Dense)            (None, 17, 2048)          4096

 dense_13 (Dense)            (None, 17, 1024)          2098176

 dense_14 (Dense)            (None, 17, 512)           524800

 dense_15 (Dense)            (None, 17, 256)           131328

 dense_16 (Dense)            (None, 17, 128)           32896

 dense_17 (Dense)            (None, 17, 64)            8256

 dense_18 (Dense)            (None, 17, 32)            2080

 dense_19 (Dense)            (None, 17, 1)             33

=================================================================
Total params: 2,801,665
Trainable params: 2,801,665
Non-trainable params: 0
_________________________________________________________________

In [ ]:
from tensorflow.keras.models import load_model

custom_objects = {'custom_loss': custom_loss}
with tf.keras.utils.custom_object_scope(custom_objects):
    # Load the best model
    best_model = load_model('best_model.h5')

# Evaluate on test data
test_results = best_model.evaluate(X_test, y_test)

# Extract MAE and MSE from the test results
test_mae = test_results[1]
test_mse = test_results[2]

print("Test MAE:", test_mae)
print("Test MSE:", test_mse)

268/268 [==============================] - 3s 8ms/step - loss: 32.1900 - mae: 4.2523 - mse: 27.9377
Test MAE: 4.252336025238037
Test MSE: 27.93766212463379