In [90]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
import tensorflow as tf
import seaborn as sns

In [144]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [145]:
data = pd.read_excel('/content/drive/MyDrive/material/complex_data_train.xlsx')
data

,realPart_1,realPart_2,realPart_3,realPart_4,realPart_5,realPart_6,realPart_7,realPart_8,realPart_9,imaginaryPart_1,imaginaryPart_2,imaginaryPart_3,imaginaryPart_4,imaginaryPart_5,imaginaryPart_6,imaginaryPart_7,imaginaryPart_8,imaginaryPart_9
0,1.007460,0.994503,1.010488,1.040534,0.976037,1.057177,1.046117,0.855888,0.292198,-0.028043,0.030954,0.002997,-0.013678,0.017569,-0.002846,-0.012238,0.005701,0
1,1.050102,1.044087,1.047392,1.028073,0.940961,1.019786,0.993707,0.848742,0.879220,-0.034597,0.036404,0.009122,-0.028541,0.015389,0.010630,-0.006132,-0.003245,0
2,1.024081,1.010774,1.021753,1.033367,0.952833,1.040350,1.033797,0.870383,0.914277,-0.027880,0.041333,0.009983,-0.015751,0.012769,-0.004342,-0.008679,-0.007700,0
3,1.037185,1.025688,1.034136,1.036172,0.941079,1.014587,1.015768,0.864382,0.778627,-0.024314,0.034993,0.008431,-0.014409,0.011825,-0.004365,0.000680,-0.013961,0
4,1.011160,1.008171,1.009467,1.017922,0.928127,1.043606,1.071710,0.902147,0.583435,-0.030014,0.034060,0.004838,-0.028636,0.021405,0.004925,-0.002480,-0.003450,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
872260,1.039154,1.031722,1.010485,0.987919,1.012234,0.989881,0.948366,0.978290,0.728979,-0.030124,0.040199,0.022217,-0.010594,0.014841,0.003605,-0.012841,-0.030286,0
872261,1.036643,1.030646,1.012156,0.993324,1.016281,0.985171,0.946559,0.980441,0.639897,-0.029622,0.044565,0.020480,-0.003433,0.020282,0.000579,-0.020967,-0.035369,0
872262,1.034097,1.030926,1.014457,0.988390,1.014610,0.986791,0.950133,0.981083,0.647148,-0.026172,0.049907,0.022070,0.000587,0.017361,-0.001063,-0.028608,-0.037572,0
872263,1.040451,1.027483,1.014592,0.994044,1.012159,0.989277,0.948840,0.970863,0.753210,-0.025337,0.044072,0.022268,-0.012234,0.011824,-0.002416,-0.011920,-0.028904,0
872264,1.041400,1.029815,1.013243,0.992607,1.011437,0.985696,0.943282,0.981204,0.589471,-0.026142,0.040851,0.017634,-0.008551,0.018261,0.003920,-0.013859,-0.035418,0

In [146]:
X_train = data.iloc[:, :-1]
X_train = X_train.astype(float)
X_train

,realPart_1,realPart_2,realPart_3,realPart_4,realPart_5,realPart_6,realPart_7,realPart_8,realPart_9,imaginaryPart_1,imaginaryPart_2,imaginaryPart_3,imaginaryPart_4,imaginaryPart_5,imaginaryPart_6,imaginaryPart_7,imaginaryPart_8
0,1.007460,0.994503,1.010488,1.040534,0.976037,1.057177,1.046117,0.855888,0.292198,-0.028043,0.030954,0.002997,-0.013678,0.017569,-0.002846,-0.012238,0.005701
1,1.050102,1.044087,1.047392,1.028073,0.940961,1.019786,0.993707,0.848742,0.879220,-0.034597,0.036404,0.009122,-0.028541,0.015389,0.010630,-0.006132,-0.003245
2,1.024081,1.010774,1.021753,1.033367,0.952833,1.040350,1.033797,0.870383,0.914277,-0.027880,0.041333,0.009983,-0.015751,0.012769,-0.004342,-0.008679,-0.007700
3,1.037185,1.025688,1.034136,1.036172,0.941079,1.014587,1.015768,0.864382,0.778627,-0.024314,0.034993,0.008431,-0.014409,0.011825,-0.004365,0.000680,-0.013961
4,1.011160,1.008171,1.009467,1.017922,0.928127,1.043606,1.071710,0.902147,0.583435,-0.030014,0.034060,0.004838,-0.028636,0.021405,0.004925,-0.002480,-0.003450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
872260,1.039154,1.031722,1.010485,0.987919,1.012234,0.989881,0.948366,0.978290,0.728979,-0.030124,0.040199,0.022217,-0.010594,0.014841,0.003605,-0.012841,-0.030286
872261,1.036643,1.030646,1.012156,0.993324,1.016281,0.985171,0.946559,0.980441,0.639897,-0.029622,0.044565,0.020480,-0.003433,0.020282,0.000579,-0.020967,-0.035369
872262,1.034097,1.030926,1.014457,0.988390,1.014610,0.986791,0.950133,0.981083,0.647148,-0.026172,0.049907,0.022070,0.000587,0.017361,-0.001063,-0.028608,-0.037572
872263,1.040451,1.027483,1.014592,0.994044,1.012159,0.989277,0.948840,0.970863,0.753210,-0.025337,0.044072,0.022268,-0.012234,0.011824,-0.002416,-0.011920,-0.028904
872264,1.041400,1.029815,1.013243,0.992607,1.011437,0.985696,0.943282,0.981204,0.589471,-0.026142,0.040851,0.017634,-0.008551,0.018261,0.003920,-0.013859,-0.035418

In [ ]:
#from sklearn.preprocessing import MinMaxScaler

# Create an instance of the MinMaxScaler
#scaler = MinMaxScaler()

# Fit the scaler on the training data and transform it
#X_train_normalized = scaler.fit_transform(X_train)

In [147]:
y_train = pd.read_excel('/content/drive/MyDrive/material/raml_train_label.xlsx')
y_train

       label_cell_train
0            Foam Board
1            Foam Board
2            Foam Board
3            Foam Board
4            Foam Board
...                 ...
872260              Wax
872261              Wax
872262              Wax
872263              Wax
872264              Wax

[872265 rows x 1 columns]

In [149]:
data1 = pd.read_excel('/content/drive/MyDrive/material/complex_data_test.xlsx')
data1

,realPart_1,realPart_2,realPart_3,realPart_4,realPart_5,realPart_6,realPart_7,realPart_8,realPart_9,imaginaryPart_1,imaginaryPart_2,imaginaryPart_3,imaginaryPart_4,imaginaryPart_5,imaginaryPart_6,imaginaryPart_7,imaginaryPart_8,imaginaryPart_9
0,1.029039,1.020027,1.020811,1.031810,0.959178,1.031924,1.015647,0.867830,0.679046,-0.028099,0.036063,0.013992,-0.018081,0.016057,-0.008864,-0.011432,-0.000049,0
1,1.007652,0.995500,1.011610,1.048908,0.974898,1.036269,1.016601,0.902939,0.874794,-0.032480,0.036684,0.010255,-0.024679,0.018943,-0.000696,0.000923,-0.009006,0
2,1.031823,1.019967,1.020385,1.019600,0.955580,1.028855,1.025078,0.880696,0.805162,-0.031704,0.033859,0.010284,-0.022877,0.013992,-0.000820,-0.002762,-0.000225,0
3,1.006084,0.996025,1.004483,1.028248,0.954615,1.006956,1.037785,0.959892,0.952146,-0.030068,0.037140,0.011360,-0.020777,0.015388,-0.001168,-0.004082,-0.007426,0
4,1.009604,1.001244,1.014710,1.045258,0.967998,1.027566,1.035237,0.895834,0.984261,-0.032421,0.033199,0.014062,-0.017424,0.015540,0.002808,-0.001400,-0.014428,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218073,1.042003,1.041220,1.029203,0.983824,1.028753,0.989966,0.913044,0.966727,0.845060,-0.029008,0.045817,0.023131,-0.010920,0.016668,-0.000355,-0.019575,-0.029978,0
218074,1.041537,1.034583,1.025448,0.987390,1.026635,0.989039,0.922721,0.971338,0.880739,-0.026570,0.047041,0.021716,-0.000774,0.016535,-0.006341,-0.025830,-0.029694,0
218075,1.039195,1.032965,1.020564,0.989197,1.024039,0.986830,0.932355,0.975407,0.888713,-0.027974,0.047707,0.019969,-0.006527,0.010904,-0.001380,-0.019965,-0.025884,0
218076,1.033436,1.026602,1.017977,0.986568,1.020980,0.991151,0.940991,0.984515,0.704706,-0.027945,0.044994,0.026969,0.003650,0.012469,-0.003788,-0.026024,-0.033621,0
218077,1.032469,1.025742,1.017548,0.990588,1.018324,0.986393,0.949456,0.982127,0.903174,-0.024549,0.045070,0.023233,-0.006063,0.014076,-0.001377,-0.024057,-0.029046,0

In [150]:
X_test = data1.iloc[:, :-1]
X_test = X_test.astype(float)

X_test

,realPart_1,realPart_2,realPart_3,realPart_4,realPart_5,realPart_6,realPart_7,realPart_8,realPart_9,imaginaryPart_1,imaginaryPart_2,imaginaryPart_3,imaginaryPart_4,imaginaryPart_5,imaginaryPart_6,imaginaryPart_7,imaginaryPart_8
0,1.029039,1.020027,1.020811,1.031810,0.959178,1.031924,1.015647,0.867830,0.679046,-0.028099,0.036063,0.013992,-0.018081,0.016057,-0.008864,-0.011432,-0.000049
1,1.007652,0.995500,1.011610,1.048908,0.974898,1.036269,1.016601,0.902939,0.874794,-0.032480,0.036684,0.010255,-0.024679,0.018943,-0.000696,0.000923,-0.009006
2,1.031823,1.019967,1.020385,1.019600,0.955580,1.028855,1.025078,0.880696,0.805162,-0.031704,0.033859,0.010284,-0.022877,0.013992,-0.000820,-0.002762,-0.000225
3,1.006084,0.996025,1.004483,1.028248,0.954615,1.006956,1.037785,0.959892,0.952146,-0.030068,0.037140,0.011360,-0.020777,0.015388,-0.001168,-0.004082,-0.007426
4,1.009604,1.001244,1.014710,1.045258,0.967998,1.027566,1.035237,0.895834,0.984261,-0.032421,0.033199,0.014062,-0.017424,0.015540,0.002808,-0.001400,-0.014428
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218073,1.042003,1.041220,1.029203,0.983824,1.028753,0.989966,0.913044,0.966727,0.845060,-0.029008,0.045817,0.023131,-0.010920,0.016668,-0.000355,-0.019575,-0.029978
218074,1.041537,1.034583,1.025448,0.987390,1.026635,0.989039,0.922721,0.971338,0.880739,-0.026570,0.047041,0.021716,-0.000774,0.016535,-0.006341,-0.025830,-0.029694
218075,1.039195,1.032965,1.020564,0.989197,1.024039,0.986830,0.932355,0.975407,0.888713,-0.027974,0.047707,0.019969,-0.006527,0.010904,-0.001380,-0.019965,-0.025884
218076,1.033436,1.026602,1.017977,0.986568,1.020980,0.991151,0.940991,0.984515,0.704706,-0.027945,0.044994,0.026969,0.003650,0.012469,-0.003788,-0.026024,-0.033621
218077,1.032469,1.025742,1.017548,0.990588,1.018324,0.986393,0.949456,0.982127,0.903174,-0.024549,0.045070,0.023233,-0.006063,0.014076,-0.001377,-0.024057,-0.029046

In [151]:
y_test = pd.read_excel('/content/drive/MyDrive/material/raml_test_label.xlsx')
y_test

       label_cell_val
0          Foam Board
1          Foam Board
2          Foam Board
3          Foam Board
4          Foam Board
...               ...
218073            Wax
218074            Wax
218075            Wax
218076            Wax
218077            Wax

[218078 rows x 1 columns]

In [152]:
from sklearn.preprocessing import LabelEncoder

# Create an instance of LabelEncoder
label_encoder = LabelEncoder()

# Fit the label encoder on the combined labels (y_train + y_test)
combined_labels = np.concatenate([y_train, y_test])
label_encoder.fit(combined_labels)

# Encode y_train and y_test
y_train_encoded = label_encoder.transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:99: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [153]:
import numpy as np
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train_encoded, test_size=0.2, random_state=42)

# Print the shapes of the datasets
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_val shape:", X_val.shape)
print("y_val shape:", y_val.shape)

X_train shape: (697812, 17)
y_train shape: (697812,)
X_val shape: (174453, 17)
y_val shape: (174453,)

In [154]:
X_train = X_train.astype('float32')
X_val = X_val.astype('float32')
X_test = X_test.astype('float32')

In [ ]:
#X_test_normalized = scaler.transform(X_test)

In [155]:
X_train.shape

(697812, 17)

In [156]:
y_train.shape

(697812,)

In [157]:
X_test.shape

(218078, 17)

In [158]:
y_test.shape

(218078, 1)

In [159]:
y_train_encoded = pd.DataFrame(y_train_encoded)
unique_labels = y_train_encoded[0].unique()
print(unique_labels)

[ 7  9 12  6  0  2  3  1  4  5  8 11 10 13]

In [160]:
y_test_encoded = pd.DataFrame(y_test_encoded)
unique_labels = y_test_encoded[0].unique()
print(unique_labels)

[ 7  9 12  6  0  2  3  1  4  5  8 11 10 13]

In [161]:
num_classes = len(label_encoder.classes_)
num_classes

14

In [162]:
# Get the class labels from the LabelEncoder
class_labels = label_encoder.classes_

# Create a dictionary mapping numerical values to class labels
numerical_to_class = dict(zip(range(num_classes), class_labels))

# Print the mapping
for numerical_value, class_label in numerical_to_class.items():
    print(f"Numerical value {numerical_value} corresponds to class label {class_label}.")

Numerical value 0 corresponds to class label Bubble Wrap.
Numerical value 1 corresponds to class label Canvas.
Numerical value 2 corresponds to class label Cardboard.
Numerical value 3 corresponds to class label Corrugated Cardboard.
Numerical value 4 corresponds to class label Crepe Paper.
Numerical value 5 corresponds to class label Felt.
Numerical value 6 corresponds to class label Fine Fabric.
Numerical value 7 corresponds to class label Foam Board.
Numerical value 8 corresponds to class label Foam Rubber.
Numerical value 9 corresponds to class label Paper Sheets.
Numerical value 10 corresponds to class label Plaster.
Numerical value 11 corresponds to class label Polypropylene.
Numerical value 12 corresponds to class label Polystyrene.
Numerical value 13 corresponds to class label Wax.

In [163]:
from tensorflow.keras.layers import concatenate

def inception_module(x, filters):
    # 1x1 convolution branch
    branch1x1 = Conv1D(filters[0], 1, activation='relu', padding='same')(x)

    # 3x3 convolution branch
    branch3x3 = Conv1D(filters[1], 1, activation='relu', padding='same')(x)
    branch3x3 = Conv1D(filters[2], 3, activation='relu', padding='same')(branch3x3)

    # 5x5 convolution branch
    branch5x5 = Conv1D(filters[3], 1, activation='relu', padding='same')(x)
    branch5x5 = Conv1D(filters[4], 5, activation='relu', padding='same')(branch5x5)

    # Concatenate branches
    x = concatenate([branch1x1, branch3x3, branch5x5], axis=-1)

    return x

In [164]:
from tensorflow.keras.layers import Input, Conv1D, MaxPooling1D, UpSampling1D, concatenate, Flatten, Dense, ZeroPadding1D

def unet_inception(input_shape):
    # Encoder
    inputs = Input(shape=input_shape)

    # Inception module
    inception = inception_module(inputs, [128, 96, 128, 96, 128])

    conv1 = Conv1D(64, 3, activation='relu', padding='same')(inception)
    conv1 = Conv1D(128, 3, activation='relu', padding='same')(conv1)
    pool1 = MaxPooling1D(pool_size=2)(conv1)

    conv2 = Conv1D(128, 5, activation='relu', padding='same')(pool1)
    conv2 = Conv1D(128, 5, activation='relu', padding='same')(conv2)
    pool2 = MaxPooling1D(pool_size=2)(conv2)

    conv3 = Conv1D(256, 7, activation='relu', padding='same')(pool2)
    conv3 = Conv1D(256, 7, activation='relu', padding='same')(conv3)
    pool3 = MaxPooling1D(pool_size=2)(conv3)

    # Decoder
    up4 = UpSampling1D(size=2)(pool3)
    concat4 = concatenate([up4, conv3], axis=-1)
    conv4 = Conv1D(256, 7, activation='relu', padding='same')(concat4)
    conv4 = Conv1D(256, 7, activation='relu', padding='same')(conv4)

    up5 = UpSampling1D(size=2)(conv4)
    concat5 = concatenate([up5, conv2], axis=-1)
    conv5 = Conv1D(128, 5, activation='relu', padding='same')(concat5)
    conv5 = Conv1D(128, 5, activation='relu', padding='same')(conv5)

    up6 = UpSampling1D(size=2)(conv5)
    padding = ZeroPadding1D(padding=(0, 1))(up6)
    concat6 = concatenate([padding, conv1], axis=-1)
    conv6 = Conv1D(128, 3, activation='relu', padding='same')(up6)
    conv6 = Conv1D(64, 3, activation='relu', padding='same')(conv6)

    flatten = Flatten()(conv6)


    dense4 = Dense(128, activation='relu')(flatten)
    dense5 = Dense(64, activation='relu')(dense4)
    dense6 = Dense(32, activation='relu')(dense5)
    dense7 = Dense(16, activation='relu')(dense6)

    # Output layer for regression
    outputs = Dense(14, activation='softmax')(dense7)

    model = tf.keras.Model(inputs=inputs, outputs=outputs)

    return model

In [165]:
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint


checkpoint = ModelCheckpoint('best_model_inception_real_imag.h5', monitor='val_loss', save_best_only=True, mode='min')
classification_model = unet_inception(input_shape = (17, 1))


classification_model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
classification_model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_val, y_val), callbacks=[checkpoint])

Epoch 1/10
21807/21807 [==============================] - 303s 13ms/step - loss: 0.8786 - accuracy: 0.6749 - val_loss: 0.5739 - val_accuracy: 0.7905
Epoch 2/10
21807/21807 [==============================] - 294s 13ms/step - loss: 0.5560 - accuracy: 0.7988 - val_loss: 0.5149 - val_accuracy: 0.8114
Epoch 3/10
21807/21807 [==============================] - 309s 14ms/step - loss: 0.5871 - accuracy: 0.8112 - val_loss: 0.5075 - val_accuracy: 0.8155
Epoch 4/10
21807/21807 [==============================] - 280s 13ms/step - loss: 0.4859 - accuracy: 0.8240 - val_loss: 0.4699 - val_accuracy: 0.8276
Epoch 5/10
21807/21807 [==============================] - 278s 13ms/step - loss: 0.4675 - accuracy: 0.8306 - val_loss: 0.4559 - val_accuracy: 0.8361
Epoch 6/10
21807/21807 [==============================] - 278s 13ms/step - loss: 0.4664 - accuracy: 0.8324 - val_loss: 0.4512 - val_accuracy: 0.8386
Epoch 7/10
21807/21807 [==============================] - 277s 13ms/step - loss: 0.4707 - accuracy: 0.8339 - val_loss: 0.4300 - val_accuracy: 0.8452
Epoch 8/10
21807/21807 [==============================] - 277s 13ms/step - loss: 0.4612 - accuracy: 0.8341 - val_loss: 0.4447 - val_accuracy: 0.8425
Epoch 9/10
21807/21807 [==============================] - 282s 13ms/step - loss: 0.4346 - accuracy: 0.8435 - val_loss: 0.4361 - val_accuracy: 0.8444
Epoch 10/10
21807/21807 [==============================] - 281s 13ms/step - loss: 0.4299 - accuracy: 0.8449 - val_loss: 0.4628 - val_accuracy: 0.8330

In [166]:
classification_model.summary()

Model: "model_7"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 input_8 (InputLayer)           [(None, 17, 1)]      0           []

 conv1d_95 (Conv1D)             (None, 17, 96)       192         ['input_8[0][0]']

 conv1d_97 (Conv1D)             (None, 17, 96)       192         ['input_8[0][0]']

 conv1d_94 (Conv1D)             (None, 17, 128)      256         ['input_8[0][0]']

 conv1d_96 (Conv1D)             (None, 17, 128)      36992       ['conv1d_95[0][0]']

 conv1d_98 (Conv1D)             (None, 17, 128)      61568       ['conv1d_97[0][0]']

 concatenate_23 (Concatenate)   (None, 17, 384)      0           ['conv1d_94[0][0]',
                                                                  'conv1d_96[0][0]',
                                                                  'conv1d_98[0][0]']

 conv1d_99 (Conv1D)             (None, 17, 64)       73792       ['concatenate_23[0][0]']

 conv1d_100 (Conv1D)            (None, 17, 128)      24704       ['conv1d_99[0][0]']

 max_pooling1d_21 (MaxPooling1D  (None, 8, 128)      0           ['conv1d_100[0][0]']
 )

 conv1d_101 (Conv1D)            (None, 8, 128)       82048       ['max_pooling1d_21[0][0]']

 conv1d_102 (Conv1D)            (None, 8, 128)       82048       ['conv1d_101[0][0]']

 max_pooling1d_22 (MaxPooling1D  (None, 4, 128)      0           ['conv1d_102[0][0]']
 )

 conv1d_103 (Conv1D)            (None, 4, 256)       229632      ['max_pooling1d_22[0][0]']

 conv1d_104 (Conv1D)            (None, 4, 256)       459008      ['conv1d_103[0][0]']

 max_pooling1d_23 (MaxPooling1D  (None, 2, 256)      0           ['conv1d_104[0][0]']
 )

 up_sampling1d_21 (UpSampling1D  (None, 4, 256)      0           ['max_pooling1d_23[0][0]']
 )

 concatenate_24 (Concatenate)   (None, 4, 512)       0           ['up_sampling1d_21[0][0]',
                                                                  'conv1d_104[0][0]']

 conv1d_105 (Conv1D)            (None, 4, 256)       917760      ['concatenate_24[0][0]']

 conv1d_106 (Conv1D)            (None, 4, 256)       459008      ['conv1d_105[0][0]']

 up_sampling1d_22 (UpSampling1D  (None, 8, 256)      0           ['conv1d_106[0][0]']
 )

 concatenate_25 (Concatenate)   (None, 8, 384)       0           ['up_sampling1d_22[0][0]',
                                                                  'conv1d_102[0][0]']

 conv1d_107 (Conv1D)            (None, 8, 128)       245888      ['concatenate_25[0][0]']

 conv1d_108 (Conv1D)            (None, 8, 128)       82048       ['conv1d_107[0][0]']

 up_sampling1d_23 (UpSampling1D  (None, 16, 128)     0           ['conv1d_108[0][0]']
 )

 conv1d_109 (Conv1D)            (None, 16, 128)      49280       ['up_sampling1d_23[0][0]']

 conv1d_110 (Conv1D)            (None, 16, 64)       24640       ['conv1d_109[0][0]']

 flatten_7 (Flatten)            (None, 1024)         0           ['conv1d_110[0][0]']

 dense_35 (Dense)               (None, 128)          131200      ['flatten_7[0][0]']

 dense_36 (Dense)               (None, 64)           8256        ['dense_35[0][0]']

 dense_37 (Dense)               (None, 32)           2080        ['dense_36[0][0]']

 dense_38 (Dense)               (None, 16)           528         ['dense_37[0][0]']

 dense_39 (Dense)               (None, 14)           238         ['dense_38[0][0]']

==================================================================================================
Total params: 2,971,358
Trainable params: 2,971,358
Non-trainable params: 0
__________________________________________________________________________________________________

In [167]:
from tensorflow.keras.models import load_model

# Load the best model
best_model = load_model('best_model_inception_real_imag.h5')

In [168]:
test_loss, test_accuracy = best_model.evaluate(X_test, y_test_encoded)
print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

6815/6815 [==============================] - 31s 4ms/step - loss: 0.4331 - accuracy: 0.8443
Test Loss: 0.43314701318740845
Test Accuracy: 0.8443217277526855